import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThirdwebProvider } from "@/app/thirdweb";
import { Sepolia } from "@thirdweb-dev/chains";
import { signer } from "@/app/connect";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create kickstarter",
  description: "Generated by create Abdi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThirdwebProvider
      activeChain={Sepolia}
      clientId="b3e93dd3314ddba56637593cc3055d23"
      signer={signer}
    >
      <html lang="en">
        <body className={inter.className}>
          <main className="m-h-screen relative"> {children}</main>
        </body>
      </html>
    </ThirdwebProvider>
  );
}
